tap "homebrew/bundle"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Command-line fuzzy finder written in Go
brew "fzf"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Simple terminal UI for git commands
brew "lazygit"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Platform built on V8 to build network applications
brew "node"
# Manage multiple Node.js versions
brew "nvm"
# Highly capable, feature-rich programming language
brew "perl"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Powerful, clean, object-oriented scripting language
brew "ruby"
# Clean C library for processing UTF-8 Unicode data
brew "utf8proc"
# Pluggable terminal workspace, with terminal multiplexer as the base feature
brew "zellij"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# Better and friendly vi(vim) mode plugin for ZSH
brew "zsh-vi-mode"
# Command-line interface for 1Password
cask "1password-cli"
# GPU-accelerated terminal emulator
cask "alacritty"
# Client for the Dropbox cloud storage service
cask "dropbox"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Window snapping tool
cask "rectangle-pro"
